spring:
  application:
    name: spring-ai-ollama
  ai:
    ollama:
      base-url: ${OLLAMA_HOST}
      chat:
        options:
          model: llama3.2
          temperature: 0.7
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers-config.json
        sse:
          connections:
            finance-mcp-server:
              url: ${MCP_FINANCE_SERVER}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    com.egon: INFO
    org.springframework.ai.mcp: DEBUG
    io.modelcontextprotocol: DEBUG

rag:
  documents-path: ${RAG_DOCUMENTS_PATH}
